projects:
  shepherd:
    schemaPath: src/hasura/schema.graphql
    extensions:
      endpoints:
        default:
          url: "http://localhost:8080/v1/graphql"
          subscription: "ws://localhost:8080/v1/graphql"
