version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-{{ .Branch }}
            - yarn-{{ .Branch }}
      - run:
          name: Place NPM registry token
          command: echo -e "//registry.npmjs.org/:_authToken=$NPMTOKEN \nscope=shepherdorg \naccess=public" > ~/.npmrc
      - run:
          name: Install lerna
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Monorepo build and publish
          command: yarn run lerna publish from-package --yes
      - run:
          name: Restore docker layer restore
          command: |
            mkdir -p /caches
            set +o pipefail
            docker load -i /caches/layercache.tar | true
      - run:
          name: Login to docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWD
      - run:
          name: Build docker images
          command: BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/build.js
      - run:
          name: Push docker images
          command: BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/deploy-docker.js
      - save_cache:
          key: yarn-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: docker-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/layercache.tar
