version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-{{ .Branch }}
      - run:
          name: Place NPM registry token
          command: echo -e "//registry.npmjs.org/:_authToken=$NPMTOKEN \nscope=shepherdorg \naccess=public" > ~/.npmrc
      - run:
          name: Install lerna
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Monorepo build and publish
          command: yarn run lerna publish from-package --yes
      - run:
          name: Build docker images
          command: ./scripts/build.js
          environment:
            BUILD_NUMBER: $CIRCLE_BUILD_NUM
      - save_cache:
          key: yarn-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
