version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
          version: 19.03.13
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Place NPM registry token
          command: echo -e "//registry.npmjs.org/:_authToken=$NPMTOKEN \nscope=shepherdorg \naccess=public" > ~/.npmrc
    #   - run:
    #       name: Set yarn cache location
    #       command: yarn config set cache-folder ~/.cache/yarn
      - run:
          name: Yarn install
          command: yarn install --immutable
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Publish to NPM
          command: yarn run lerna publish from-package --yes
      - run:
          name: Restore docker layer restore
          command: |
            set +o pipefail
            docker load -i /tmp/layercache.tar | true
      - run:
          name: Login to docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWD
      - run:
          name: Build docker images
          command: BASE_COMMIT=$(./scripts/base-commit.sh) BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/build.js
      - run:
          name: Push docker images
          command: BASE_COMMIT=$(./scripts/base-commit.sh) BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/push-docker.js
      - run:
          name: Save Docker Layer Cache
          command: BASE_COMMIT=$(./scripts/base-commit.sh) ./scripts/save-docker-cache.js --only-changed > /tmp/layercache.tar
      - save_cache:
          key: docker-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/layercache.tar
