version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ .Branch }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Place NPM registry token
          command: echo -e "//registry.npmjs.org/:_authToken=$NPMTOKEN \nscope=shepherdorg \naccess=public" > ~/.npmrc
      - run:
          name: Install lerna
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Monorepo build and publish
          command: yarn run publish from-git --yes
      - save_cache:
          key: yarn-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
