version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-{{ .Branch }}
            - yarn-{{ .Branch }}
      - run:
          name: Place NPM registry token
          command: echo -e "//registry.npmjs.org/:_authToken=$NPMTOKEN \nscope=shepherdorg \naccess=public" > ~/.npmrc
      - run:
          name: Install lerna
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Build
          command: yarn run lerna run tsc --since $(./scripts/base-commit.sh) --include-dependencies --stream
      - run:
          name: Publish to NPM
          command: yarn run lerna publish from-package --yes
      - run:
          name: Restore docker layer restore
          command: |
            set +o pipefail
            docker load -i /tmp/layercache.tar | true
      - run:
          name: Login to docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWD
      - run:
          name: Build docker images
          command: BASE_COMMIT=$(./scripts/base-commit.sh) BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/build.js --only-changed
      - run:
          name: Push docker images
          command: BASE_COMMIT=$(./scripts/base-commit.sh) BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/deploy-docker.js --only-changed
      - run:
          name: Save Docker Layer Cache
          command: BASE_COMMIT=$(./scripts/base-commit.sh) ./scripts/save-docker-cache.js --only-changed > /tmp/layercache.tar
      - save_cache:
          key: yarn-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: docker-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/layercache.tar
