apiVersion: v1
kind: Service
metadata:
  name: shepherd-ui-api-service
  labels:
    name: shepherd-ui-api-service
    environment: {{ENV}}
spec:
  ports:
    - port: 80
      name: serviceport
      targetPort: 8080
      protocol: TCP
  selector:
    app: shepherd-ui-api-service-pod
    environment: {{ENV}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shepherd-ui-api-service-deployment
  annotations:
    kubernetes.io/change-cause: {{TAG_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shepherd-ui-api-service-pod
        environment: {{ENV}}
    spec:
      containers:
        - name: shepherd-ui-api-service-pod
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: {{SHEPHERD_UI_POSTGRES_URL}}
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: startup, http-log, webhook-log, websocket-log, query-log
          ports:
            - containerPort: 8080
              name: service-port
          livenessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 15
            timeoutSeconds: 4
            failureThreshold: 2
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 15
            timeoutSeconds: 4
  selector:
    matchLabels:
      app: shepherd-ui-api-service-pod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shepherd-ui-api-path-ingress
  namespace: default
  labels:
    app: shepherd-ui-api-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /{{DOLLARSIGN}}2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{INTERNAL_API_FQDN}}
      http:
        paths:
          - path: /shepherd-ui-api(/|$)(.*)
            backend:
              service:
                name: shepherd-ui-api-service
                port:
                  number: 80
            pathType: Prefix

