apiVersion: v1
kind: Service
metadata:
  name: shepherd-ui-service
  labels:
    name: shepherd-ui-service
    environment: {{ENV}}
spec:
  ports:
    - port: 80
      name: serviceport
      targetPort: 3000
      protocol: TCP
  selector:
    app: shepherd-ui-service-pod
    environment: {{ENV}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shepherd-ui-service-deployment
  annotations:
    kubernetes.io/change-cause: {{TAG_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shepherd-ui-service-pod
        environment: {{ENV}}
    spec:
      containers:
        - name: shepherd-ui-service-pod
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          env:
            - name: HASURA_ENDPOINT_URL
              value: wss://{{INTERNAL_API_FQDN}}/shepherd-ui-api/v1/graphql
          ports:
            - containerPort: 3000
              name: service-port
          livenessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 15
            timeoutSeconds: 4
            failureThreshold: 2
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 15
            timeoutSeconds: 4
  selector:
    matchLabels:
      app: shepherd-ui-service-pod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shepherd-ui-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: shepherd-ui{{SERVICE_SUFFIX}}
      http:
        paths:
          - backend:
              service:
                name: shepherd-ui-service
                port:
                  number: 80
            pathType: Prefix
            path: /

